name: Report usage to Stripe

#TODO: double check cron 
on:
    schedule: 
        - cron: '0 12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://krets.app/api/payment/report'
        method: 'POST'
        bearerToken: ${{ secrets.USAGE_REPORT_SECRET_TOKEN }}

